### ISSUE TITLE
Download link geht nicht

### ISSUE THREAD

**Issue by marius137** [Senmou/pr0ball-remake#7]
Benutz am besten das releases feature um die apk zu verteilen

**Comment by LonelyChimo302** [comment]
Immernoch noch nicht

**Comment by Senmou** [comment]
Ich werde das release feature beim nächsten Update (kommendes Wochenende) dann nutzen. Die alte .apk hab ich dummerweise gelöscht, darum wird es bis zum Wochenende keinen Download geben.
